version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3-node
    steps:
      - checkout
      - run: yarn install --ignore-engines
      - run: yarn eslint
      - run: yarn test

  # end to end tests. These are sepparated because they take longer since chrome needs to be launched
  test_user:
    docker:
      - image: circleci/python:3-node
    steps:
      - checkout
      - run: 'sh .circleci/setup_puppeteer.sh'
      - run: yarn install --ignore-engines
      - run: yarn run test:integration

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - test_user
