version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3-node
    steps:
      - checkout
      - run: yarn install --ignore-engines
      - run: yarn test

  deploy:
    docker:
      - image: circleci/python:3-node
    steps:
      - checkout
      - run: bash .circleci/deploy.sh

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              # No branch commit will ever trigger this job.
              ignore: /.*/
            tags:
              only: /v.*/
