version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3-node
    steps:
      - checkout
      - run: yarn install --ignore-engines
      - run: yarn test

  # end to end tests. These are sepparated because they take longer since chrome needs to be launched
  test_user:
    docker:
      - image: circleci/python:3-node
    steps:
      - checkout
      - run: 'sh .circleci/setup_puppeteer.sh'
      - run: yarn install --ignore-engines
      - run: yarn run test:integration

  deploy:
    docker:
      - image: circleci/python:3-node
    steps:
      - checkout
      - run: bash .circleci/verify_tag.sh
      - run: bash .circleci/deploy.sh

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          filters:
            # To allow tag commits whose name start with "v" to trigger
            # "test" job, an explicit "tags" filter is required here.
            tags:
              only: /v.*/
      - test_user:
          filters:
            tags:
              only: /v.*/
      - deploy:
          requires:
            - test
            - test_user
          filters:
            branches:
              # No branch commit will ever trigger this job.
              ignore: /.*/
            tags:
              only: /v.*/
