version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3-node
    steps:
      - checkout
      - run: yarn install --ignore-engines

      # TODO: Maybe fix this? Or at least delete this comment
      - run: CI=false yarn run build
      - run: pip install awscli --upgrade --user

      # I'm not sure why it installs here but it does...
      - run: ~/.local/bin/aws s3 sync build s3://staging.refine.bio --delete --acl public-read
