version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3-node
    steps:
      - checkout
      - run: pip install awscli --upgrade --user
      - run: yarn install --ignore-engines
      - run: yarn run build
      - run: aws s3 sync build s3://$AWS_S3_BUCKET_PATH --delete
