version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn install
      - run: yarn run build
      - run: aws s3 sync build s3://$AWS_S3_BUCKET_PATH --delete
