const initialState = {
  experiments: [
    {
      id: 1,
      title:
        'Integrated bioinformatic and wet-lab approach to identify potential oncogenic networks in neuroblastoma and other tumors',
      description:
        'This SuperSeries is composed of the SubSeries listed below. Refer to individual Series',
      accession_code: 'E-GEOD-16254',
      platform_accession_code: 'A-AFFY-44',
      source_database: 'ARRAY_EXPRESS',
      source_url:
        'https://www.ebi.ac.uk/arrayexpress/json/v3/experiments/E-GEOD-16254',
      platform_name:
        'Affymetrix GeneChip Human Genome U133 Plus 2.0 [HG-U133_Plus_2]',
      has_publication: false,
      publication_title: '',
      publication_doi: '',
      pubmed_id: '',
      samples: [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69,
        70,
        71,
        72,
        73,
        74,
        75,
        76,
        77,
        78,
        79,
        80,
        81,
        82,
        83,
        84,
        85,
        86,
        87,
        88
      ],
      submitter_institution: 'Academic Medical Centre, University of Amsterdam',
      created_at: '2018-04-19T18:46:47.666345Z',
      last_modified: '2018-04-19T18:46:48.309913Z'
    },
    {
      id: 2,
      title:
        'Transcription profiling of human neuroblast tumours reveals two distinct gene signatures identify malignant Neuroblast and Schwannian stromal cells',
      description:
        'Tumor tissue heterogeneity is a well known feature of several solid tumors. Neuroblastic Tumors (NTs) is a group of paediatric cancers with a great tissue heterogeneity. Most of NTs are composed of undifferentiated, poorly differentiated or differentiating neuroblastic (Nb) cells with very few or absent Schwannian stromal (SS) cells: these tumors are grouped as Neuroblastoma (Schwannian stroma-poor). The remaining NTs are composed of abundant SS cells and classified as Ganglioneuroblastoma (Schwannian stroma-rich) intermixed or nodular and Ganglioneuroma. The importance to understand Nb and SS gene signatures in NTs, is to clarify the complex network mechanism of tumor growth and progression. In order to identify the Nb and SS cells gene signatures, we analyzed the gene expression profiling of 19 cases of neuroblastic tumors: 10 stroma poor (NTs-SP) and 9 stroma rich (NTs-SR), by high density oligonucleotide microarrays. Moreover, the analysis was performed in parallel on both whole and laser microdissected tumor samples: from 4 of 19 cases, was isolated different areas all composed of pure cellular populations. We performed genome wide expression analysis by using Affymetrix technology and we used two different approaches for data analysis: SAM (Significance Analysis of Microarrays) and a method based on Game Theory (GT), to identify genes differently expressed in SS and Nb cells. Differently from the SAM method, the analysis based on GT (Moretti et al. (2006)) gives the advantage of selecting relevant genes not only according to the expression profile of each single gene, but considering also gene interaction. Experiment Overall Design: Tissue samples from 10 primary neuroblastoma stroma-poor (NTs-SP) and 9 ganglioneuroblastoma/ganglioneuroma stroma-rich (NTs-SR) tumors, were obtained at diagnosis from patients at different clinical stage. Frozen samples of NTs-SP had a minimum content of 90% of malignant cells, while NTs-SR had more than 80-90% of schwannian stromal cells. Four out of 19 NTs: 2 neuroblastomas (Schwannian stoma-poor) and 2 ganglioneublastomas (Schwannian stroma-rich), were further analyzed with laser microdissection.',
      accession_code: 'E-GEOD-7529',
      platform_accession_code: 'A-AFFY-33',
      source_database: 'ARRAY_EXPRESS',
      source_url:
        'https://www.ebi.ac.uk/arrayexpress/json/v3/experiments/E-GEOD-7529',
      platform_name: 'Affymetrix GeneChip Human Genome HG-U133A [HG-U133A]',
      has_publication: false,
      publication_title: '',
      publication_doi: '',
      pubmed_id: '',
      samples: [
        89,
        90,
        91,
        92,
        93,
        94,
        95,
        96,
        97,
        98,
        99,
        100,
        101,
        102,
        103,
        104,
        105,
        106,
        107,
        108,
        109,
        110,
        111,
        112,
        113,
        114,
        115,
        116
      ],
      submitter_institution: 'National Institute for Cancer Research (IST)',
      created_at: '2018-04-19T18:46:56.213486Z',
      last_modified: '2018-04-19T18:46:56.733813Z'
    },
    {
      id: 3,
      title: 'Transcription profiling of human neuroblastic tumors',
      description:
        'The expression profiles of 64 neuroblastic tumors (mainly neuroblastoma) were determined on Affymetrix chips HG U133 Plus 2.0. Experiment Overall Design: 64 neuroblastic tumors',
      accession_code: 'E-GEOD-12460',
      platform_accession_code: 'A-AFFY-44',
      source_database: 'ARRAY_EXPRESS',
      source_url:
        'https://www.ebi.ac.uk/arrayexpress/json/v3/experiments/E-GEOD-12460',
      platform_name:
        'Affymetrix GeneChip Human Genome U133 Plus 2.0 [HG-U133_Plus_2]',
      has_publication: true,
      publication_title:
        'Somatic and germline activating mutations of the ALK kinase receptor in neuroblastoma.',
      publication_doi: '18923523',
      pubmed_id: '18923523',
      samples: [
        117,
        118,
        119,
        120,
        121,
        122,
        123,
        124,
        125,
        126,
        127,
        128,
        129,
        130,
        131,
        132,
        133,
        134,
        135,
        136,
        137,
        138,
        139,
        140,
        141,
        142,
        143,
        144,
        145,
        146,
        147,
        148,
        149,
        150,
        151,
        152,
        153,
        154,
        155,
        156,
        157,
        158,
        159,
        160,
        161,
        162,
        163,
        164,
        165,
        166,
        167,
        168,
        169,
        170,
        171,
        172,
        173,
        174,
        175,
        176,
        177,
        178,
        179,
        180
      ],
      submitter_institution: 'Institut Curie',
      created_at: '2018-04-19T18:47:02.212132Z',
      last_modified: '2018-04-19T18:47:02.799251Z'
    }
  ]
};

export default (state = initialState, action) => {
  switch (action.type) {
    default:
      return state;
  }
};
